# Generated by Django 4.0.8 on 2023-02-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nome do consultório:')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail do consultório:')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Telefone do consultório:')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço do consultório')),
                ('default_message_cancel', models.TextField(blank=True, verbose_name='Mensagem padrão de cancelamento')),
                ('time_per_service', models.TimeField(blank=True, null=True, verbose_name='Tempo por atendimento')),
                ('morning_start', models.TimeField(blank=True, null=True, verbose_name='Inicio manhã')),
                ('morning_end', models.TimeField(blank=True, null=True, verbose_name='Fim manhã')),
                ('afternoon_start', models.TimeField(blank=True, null=True, verbose_name='Inicio tarde')),
                ('afternoon_end', models.TimeField(blank=True, null=True, verbose_name='Fim tarde')),
                ('night_start', models.TimeField(blank=True, null=True, verbose_name='Inicio noite')),
                ('night_end', models.TimeField(blank=True, null=True, verbose_name='Fim noite')),
            ],
        ),
    ]
